language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com"
- sudo apt-get update -qq
- sudo apt-get install libspdlog-dev -y
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u$USERNAME:$BINTRAY_API_KEY
    "https://api.bintray.com/content/$USERNAME/otus-cpp/helloworld/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb"